[package]
name = "usysconf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.8.0"
bincode = "1.3.3"
clap = "4.4.5"
futures = "0.3.28"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
thiserror = "1.0.48"

[[bin]]
name = "usysconf"
path = "src/bin/usysconf/main.rs"
